### ISSUE TITLE
Golang "context" import in separate files.

### ISSUE THREAD

**Issue by amricko0b** [infobloxopen/protoc-gen-gorm#131]
Hello everyone!

I've go my messages model and services in seprated *.proto files.
Hence, after compilation I have two *.pb.gorm.go files - with structures and with autogenerated CRUD services. Both of them - in the same package.

Trouble: Golang's package "context" is imported in *.pb.gorm.go file with structures but none of him found in file with services. 

It produces a compilation error, because context is undefined.
Am I able to fix this somehow ? Or so, should I keep everything in one *.proto file ?

**Comment by dkukharau** [comment]
Hi again!
Thanks for filling this!
I've checked the code and it seems that  it's a bug on our side, so we will fix it as soon as have capacity.
If it's a blocker for you, then yes, you can put everything in one file until the fix is delivered.

**Comment by amricko0b** [comment]
@dkukharau 
I will contribute with pleausure, please, tell me more about that.

**Comment by Calebjh** [comment]
We use custom import handling (because there was an issue using the existing protoc-gen-go plugin import handling with multiple packages with the same name having the same import alias that I couldn't resolve).

We'll need to add a `p.UsingGoImports("context")` probably in this function: https://github.com/infobloxopen/protoc-gen-gorm/blob/c71fa2e99b9da3dcb839cc2faf6b03ea6dd9a5d9/plugin/servergen.go#L96

**Comment by dkukharau** [comment]
Thanks @Calebjh for your assist.
@amricko0b 
I think this is the correct line:
https://github.com/infobloxopen/protoc-gen-gorm/blob/c71fa2e99b9da3dcb839cc2faf6b03ea6dd9a5d9/plugin/servergen.go#L107
We should generate "context" import only when there are some grpc methods to generate.
In addition, could you add a new example proto file with a grpc method defined to `example/feature_demo` directory so we see that the fix is working? (you should use messages from another file as it's request/response). You would also need to update Makefile to get the file generated by `example` target:
https://github.com/infobloxopen/protoc-gen-gorm/blob/c71fa2e99b9da3dcb839cc2faf6b03ea6dd9a5d9/Makefile#L50
After making the changes please execute `make test` to make sure everything is working and then submit a PR. Thanks for your interest!

**Comment by amricko0b** [comment]
PR: https://github.com/infobloxopen/protoc-gen-gorm/pull/133
