### ISSUE TITLE
Why using `CamelCase` for `FiledMask`?

### ISSUE THREAD

**Issue by molon** [infobloxopen/protoc-gen-gorm#145]
https://github.com/infobloxopen/protoc-gen-gorm/blob/3d81b1383306c8071aab892024a3c9f17cd8f95c/plugin/handlergen.go#L226

This is not same with `filedSelection`. and the name is `fields` not `_fields`
It is confusing before learning the source code.

**Comment by Calebjh** [comment]
Regarding the first, FieldMasks are camel cased and expected to be camel cased here because of the code expected to populate the field masks (https://github.com/infobloxopen/atlas-app-toolkit/blob/master/gateway/field_presence.go and https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/fieldmask.go). 
For FieldSelection, the usage of `_fields` is, I believe, so that the gateway won't try to auto-fill it and break if the syntax/type is "wrong". Not using camel-case there was done independently. Our documentation could still use more work.

Regarding the second question, using a `nil` field selection in `DefaultReadFoo(ctx, &Foo{Id: in.GetId()}, db, nil)` not working as expected when some fields are set to `preload:false`, that does seem like a tricky situation. I'm not sure of a good solution, though.

**Comment by molon** [comment]
Regarding the second question, maybe the pr will help. :
https://github.com/infobloxopen/atlas-app-toolkit/pull/149
```
DefaultReadShop(ctx, &Shop{Id: in.GetId()}, db,
		&infoblox_api.FieldSelection{
			Fields:map[string]*infoblox_api.Field{
				"_assoc":nil,
			}
		},
	)
```

**Comment by saltbo** [comment]
Now, It's not CamelCase. we should use the raw key https://github.com/grpc-ecosystem/grpc-gateway/pull/1049
