### ISSUE TITLE
Imports handling

### ISSUE THREAD

**Issue by dkukharau** [infobloxopen/protoc-gen-gorm#15]
Imports could be handled a bit more elegantly with the use of [PluginImports](https://godoc.org/github.com/gogo/protobuf/protoc-gen-gogo/generator#PluginImports) mixin.
e.g.

```golang
func (p *ormPlugin) Generate(file *generator.FileDescriptor) {
        ...
	p.PluginImports = generator.NewPluginImports(p.Generator)
        p.gormPkgName = generator.NewImport("github.com/jinzhu/gorm")
        p.lftPkgName = generator.NewImport("github.com/Infoblox-CTO/ngp.api.toolkit/op/gorm")
        ...
}
```
Unique package aliases will be generated for both imports.
Implementation of 
```golang
func (p *ormPlugin) GenerateImports(file *generator.FileDescriptor)
```
 is not required, it's supplied by the mixin.
[Check out](https://github.com/gogo/protobuf/blob/master/plugin/gostring/gostring.go#L140) how protoc-gen-gogo plugins use it.

**Comment by Calebjh** [comment]
I was using this, but ran into a block when I wanted to import both the `jinzhu/gorm` and `ngp.api.toolkit/op/gorm` packages, as both were aliased to `gorm1` instead of actually unique names. I may have made a mistake, but I couldn't get it to resolve that issue. I agree that import handling could be more elegant, however, as right now packages may be imported with both an alias and _

**Comment by dkukharau** [comment]
Ok, got it, though it's strange that it doesn't generate unique aliases. I will try to reproduce this.
