### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by charlesgreen** [infobloxopen/protoc-gen-gorm#176]
Hello, 
Is this project still under planned development?

If yes, I'd like to help fix some of these issues with the recent Go Modules and API changes. 

I'd like to help because I'd like to use this approach for a project I'm working on. 

Many thanks,
Charles

**Comment by Calebjh** [comment]
There's not a lot of ongoing development, it's mostly bug fixing and minor improvements.

There are a few significant issues (#98 and #174) surrounding changes to the underlying Protobuf library that would be good to fix, but there's just not enough motivation from our (Infoblox) side to invest the needed time for that, since it works stably for our most common use cases.

I try to leave helpful comment and merge good PRs, but sometimes I'm a bit slow about it.

**Comment by charlesgreen** [comment]
Thanks for the reply. I'll look at the tickets and submit PR's.
