### ISSUE TITLE
XXX.pb.gorm.go，package name error

### ISSUE THREAD

**Issue by aloha1003** [infobloxopen/protoc-gen-gorm#189]
My Command :
`protoc -I. -I$GOPATH/src --proto_path=.  --gorm_out=engine=grpc.orm:proto  --go_out=plugins=grpc:proto --proto_path=. *.proto`

But  I got  XXX.pb.gorm.go  , but it package is 

`package __grpc`

My Sample Proto FIle 

`
syntax = "proto3";
package grpc.orm;
import "google/protobuf/timestamp.proto";
import "github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto";

option go_package = ".;grpc";
message Example {
	option (gorm.opts) = {ormable: true};
	int64 id = 1;
	int64 type = 2;
	string logic_class = 3;
	string name = 4;
	
}
`

**Comment by mayuresh82** [comment]
any resolution to this ?

**Comment by Calebjh** [comment]
The package names are not specially handled by protoc-gen-gorm, and follow the same rules as protoc-gen-go. This appears to be an issue with the defined `go_package`, namely that it isn't treating `.` as a valid path, so it is converting `.;` into `__`. If you drop the `.;` or replace `.` with the actual directory path, it should render the expected package name, although then you might have to figure out the appropriate values for `--go_out` and `--gorm_out`. There's probably more info about that in the other proto repos, since this isn't an issue specific to protoc-gen-gorm.
