### ISSUE TITLE
Do you have any plans to support GormV2 version?

### ISSUE THREAD

**Issue by SliverHorn** [infobloxopen/protoc-gen-gorm#192]
Do you have any plans to support GormV2 version?

**Comment by Calebjh** [comment]
I actually hadn't seen the release Gorm V2. Thanks for pointing it out to me.
There are several improvements and updates I would like to make and hope to sooner or later. But they aren't really "planned", because I anticipate they will take a lot of time to do right. This is now added to that list.
- Upgrade the protobuf library dependencies (I think this would resolve several open issues, but the protobuf library changes were pretty significant)
- Replace the line-by-line print statements with Golang templates where possible for readability
- Support Gorm V2

**Comment by SliverHorn** [comment]
Thank you
