### ISSUE TITLE
generated GORM models should embed `gorm.Model`

### ISSUE THREAD

**Issue by dmacthedestroyer** [infobloxopen/protoc-gen-gorm#35]
Seems like a commonsense good idea to stick to the canonical way that the Gorm docs say to use it.

Are there any good reasons why we didn't do it that way?

**Comment by molon** [comment]
`DeletedAt` is indispensable sometimes

**Comment by Calebjh** [comment]
Indeed! Sometimes `DeletedAt` and soft-deletes are the way to go. However, this isn't _always_ the case, so instead of including the `gorm.Model` by default, when the situation arises, it should be included by having a `google.protobuf.Timestamp deleted_at = X;` field in your orm-able proto message.
